name=AsyncHTTPClientLight
version=2.0.0
author=Davide
maintainer=Copida Soft [copida.soft@gmail.com]
sentence=Libreria HTTP asincrona e sincrona per ESP32, con supporto a redirect, chunked transfer, header personalizzati e logging.
paragraph=Supporto GET/POST, HTTPS, redirect, retry, logging
category=Communication
url=https://github.com/copida/AsyncHTTPClientLight
architectures=esp32


